// Generated by CoffeeScript 1.6.3
/*
@author Your Name <email@example.com>
@license LICENSE
*/

var define;

define = (function(root, module) {
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    if (typeof module === 'object' && module.exports) {
      return function(factory) {
        return module.exports = factory();
      };
    } else {
      return function(factory) {
        return root.TzTime = factory();
      };
    }
  }
})(this, module);

define(function(require) {
  var TzTime;
  return TzTime = (function() {
    TzTime.prototype = Date.prototype;

    function TzTime(yr, mo, dy, hr, mi, se, ms) {
      var instance;
      if (hr == null) {
        hr = 0;
      }
      if (mi == null) {
        mi = 0;
      }
      if (se == null) {
        se = 0;
      }
      if (ms == null) {
        ms = 0;
      }
      switch (arguments.length) {
        case 0:
          instance = new Date();
          break;
        case 1:
          instance = new Date(yr);
          break;
        case 2:
          throw new Error("Not implemented yet");
          break;
        default:
          instance = new Date(yr, mo, dy, hr, mi, se, ms);
      }
      return instance;
    }

    return TzTime;

  })();
});
