// Generated by CoffeeScript 1.6.3
var TzTime, assert, chai, root;

root = this;

if (typeof require !== "undefined" && require !== null) {
  chai = require('chai');
  TzTime = require('../tztime');
}

assert = chai.assert;

describe('TzTime', function() {
  describe('constructor', function() {
    it('should be identical to Date constructor', function() {
      var d1, d2;
      d1 = new TzTime(2013, 8, 1);
      d2 = new Date(2013, 8, 1);
      return assert.equal(d1.getTime(), d2.getTime());
    });
    it('should have a constructor of TzTime', function() {
      var d;
      d = new TzTime(2013, 8, 1);
      return assert.equal(d.constructor, TzTime);
    });
    it('should be an instance of TzTime', function() {
      var d;
      d = new TzTime(2013, 8, 1);
      return assert.ok(d instanceof TzTime);
    });
    it('should also be an instance of Date', function() {
      var d;
      d = new TzTime(2013, 8, 1);
      return assert.ok(d instanceof Date);
    });
    it('should be usable withough the new keyword', function() {
      var d, d1;
      d = TzTime(2013, 8, 1);
      assert.equal(typeof d, 'object');
      assert.equal(d.constructor, TzTime);
      assert.ok(d instanceof TzTime);
      assert.ok(d instanceof Date);
      d1 = new TzTime(2013, 8, 1);
      return assert.equal(d.getTime(), d1.getTime());
    });
    it('should accept the timezone as last argument', function() {
      var d;
      d = new TzTime(2013, 8, 1, 12, 45, 39, 0, 360);
      return assert.equal(d.timezone, 360);
    });
    it('should create a new instance if passed Date or TzTime obj', function() {
      var d1, d2, d3, d4;
      d1 = new Date(2013, 8, 1);
      d2 = new TzTime(2013, 8, 1);
      d3 = new TzTime(d1);
      d4 = new TzTime(d2);
      assert.notEqual(d1, d2);
      assert.notEqual(d1, d3);
      assert.notEqual(d1, d4);
      assert.notEqual(d2, d3);
      assert.notEqual(d2, d4);
      assert.notEqual(d3, d4);
      assert.equal(d1.getTime(), d2.getTime());
      assert.equal(d1.getTime(), d3.getTime());
      return assert.equal(d1.getTime(), d4.getTime());
    });
    return it('should retain timezone when passed TzTime instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1);
      d.timezone = -240;
      d1 = new TzTime(d);
      return assert.equal(d1.timezone, -240);
    });
  });
  describe('#timezone', function() {
    it('is a number', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      return assert.equal(typeof d.timezone, 'number');
    });
    it('should be opposite of #getTimezoneOffset()', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      return assert.equal(d.getTimezoneOffset() + d.timezone, 0);
    });
    it('can be set by assigning', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.timezone = 12;
      assert.equal(d.getTimezoneOffset() + d.timezone, 0);
      return assert.equal(d.getTimezoneOffset(), -12);
    });
    it('should work correctly', function() {
      var d, lochr, pzone, utchr;
      pzone = TzTime.platformZone;
      d = new TzTime(2013, 8, 1, 8, 20);
      utchr = d.getUTCHours();
      lochr = d.getHours();
      assert.equal(d.timezone, pzone);
      d.timezone = pzone + 120;
      assert.equal(d.getUTCHours(), utchr);
      assert.equal(d.getHours(), lochr + 2);
      d.setHours(d.getHours() - 2);
      assert.equal(d.timezone, pzone + 120);
      assert.equal(d.getHours(), lochr);
      return assert.equal(d.getUTCHours(), utchr - 2);
    });
    it('should shift the time when set', function() {
      var d, h1, h2;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.timezone = 0;
      h1 = d.getHours();
      d.timezone = 60;
      h2 = d.getHours();
      return assert.equal(h1 + 1, h2);
    });
    it('will convert floats to integers', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.timezone = 120.4;
      return assert.equal(d.timezone, 120);
    });
    it('can be set using -= and += operators', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.timezone = 0;
      d.timezone += 12;
      return assert.equal(d.timezone, 12);
    });
    return it('should be UTC time if set to 0', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.timezone = 0;
      d.setHours(8);
      assert.equal(d.getUTCHours(), 8);
      return assert.equal(d.getHours(), 8);
    });
  });
  describe('#getTimezoneOffset()', function() {
    return it('should return the opposite of time zone offset', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.timezone = 12;
      return assert.equal(d.getTimezoneOffset(), -12);
    });
  });
  describe('#setTimezoneOffset()', function() {
    return it('should set the timezone using opposite of offset', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.timezone = 0;
      d.setTimezoneOffset(12);
      return assert.equal(d.timezone, -12);
    });
  });
  describe('#setFullYear()', function() {
    it('should set the year and return instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1, 8, 20);
      d1 = d.setFullYear(2020);
      assert.equal(d1, d);
      return assert.equal(d.getFullYear(), 2020);
    });
    return it('should set mont and date if passed', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.setFullYear(2015, 2, 12);
      assert.equal(d.getFullYear(), 2015);
      assert.equal(d.getMonth(), 2);
      return assert.equal(d.getDate(), 12);
    });
  });
  describe('#setMonth()', function() {
    it('should set month and return instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1, 8, 20);
      d1 = d.setMonth(9);
      assert.equal(d.getMonth(), 9);
      return assert.equal(d1, d);
    });
    return it('should set both month and date if passed both', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      d.setMonth(9, 12);
      assert.equal(d.getMonth(), 9);
      return assert.equal(d.getDate(), 12);
    });
  });
  describe('#setDate()', function() {
    return it('should set the date and return instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1, 8, 20);
      d1 = d.setDate(2);
      assert.equal(d.getDate(), 2);
      return assert.equal(d1, d);
    });
  });
  describe('#setHours()', function() {
    it('should set hours and return instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1, 8, 20);
      d1 = d.setHours(2);
      assert.equal(d.getHours(), 2);
      return assert.equal(d1, d);
    });
    return it('should set minutes, seconds, and milliseconds if given', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.setHours(2, 2, 2, 2);
      assert.equal(d.getHours(), 2);
      assert.equal(d.getMinutes(), 2);
      assert.equal(d.getSeconds(), 2);
      return assert.equal(d.getMilliseconds(), 2);
    });
  });
  describe('#setMinutes()', function() {
    it('should set minutes and return instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1, 8, 20);
      d1 = d.setMinutes(2);
      assert.equal(d.getMinutes(), 2);
      return assert.equal(d1, d);
    });
    return it('should set seconds and milliseconds if given', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.setMinutes(2, 2, 2);
      assert.equal(d.getMinutes(), 2);
      assert.equal(d.getSeconds(), 2);
      return assert.equal(d.getMilliseconds(), 2);
    });
  });
  describe('#setSeconds()', function() {
    it('should set seconds and return instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1, 8, 20);
      d1 = d.setSeconds(2);
      assert.equal(d.getSeconds(), 2);
      return assert.equal(d1, d);
    });
    return it('should set milliseconds if given', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.setSeconds(2, 2);
      assert.equal(d.getSeconds(), 2);
      return assert.equal(d.getMilliseconds(), 2);
    });
  });
  describe('#setMilliseconds()', function() {
    return it('should set milliseconds and return instance', function() {
      var d, d1;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d1 = d.setMilliseconds(2);
      assert.equal(d.getMilliseconds(), 2);
      return assert.equal(d1, d);
    });
  });
  describe('#getHours()', function() {
    return it('should give time in instance timezone', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      assert.equal(d.getHours(), 8);
      d.timezone += 120;
      assert.equal(d.getHours(), 10);
      d.timezone -= 300;
      return assert.equal(d.getHours(), 5);
    });
  });
  describe('#year', function() {
    it('should set year', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.year = 2020;
      return assert.equal(d.getFullYear(), 2020);
    });
    it('should return year', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20);
      return assert.equal(d.year, 2013);
    });
    return it('can be used with -= and += operators', function() {
      var d, y1, y2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.year -= 2;
      y1 = d.year;
      d.year += 4;
      y2 = d.year;
      assert.equal(y1, 2011);
      return assert.equal(y2, 2015);
    });
  });
  describe('#month', function() {
    it('should set month', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.month = 9;
      return assert.equal(d.getMonth(), 9);
    });
    it('should return month', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      return assert.equal(d.month, 8);
    });
    it('can be used with -= and += operators', function() {
      var d, m1, m2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.month -= 2;
      m1 = d.month;
      d.month += 4;
      m2 = d.month;
      assert.equal(m1, 6);
      return assert.equal(m2, 10);
    });
    return it('should adjust the year when incremented or decremented', function() {
      var d, y1, y2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.month -= 12;
      y1 = d.year;
      d.month += 24;
      y2 = d.year;
      assert.equal(y1, 2012);
      return assert.equal(y2, 2014);
    });
  });
  describe('#date', function() {
    it('should set the date', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.date = 20;
      return assert.equal(d.getDate(), 20);
    });
    it('should return the date', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      return assert.equal(d.date, 1);
    });
    it('can be used with -= and += operators', function() {
      var d, d1, d2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.date += 12;
      d1 = d.date;
      d.date -= 4;
      d2 = d.date;
      assert.equal(d1, 13);
      return assert.equal(d2, 9);
    });
    it('should cross month boundaries when setting', function() {
      var d, m1, m2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.date += 31;
      m1 = d.month;
      d.date -= 62;
      m2 = d.month;
      assert.equal(m1, 9);
      return assert.equal(m2, 7);
    });
    return it('should cross year boundaries when setting', function() {
      var d, y1, y2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.date += 365;
      y1 = d.year;
      d.date -= 2 * 365;
      y2 = d.year;
      assert.equal(y1, 2014);
      return assert.equal(y2, 2012);
    });
  });
  describe('#hours', function() {
    it('should set the hour', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.hours = 2;
      return assert.equal(d.getHours(), 2);
    });
    it('should return hour', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      return assert.equal(d.hours, 8);
    });
    it('can be used with -= and += operators', function() {
      var d, h1, h2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.hours -= 4;
      h1 = d.hours;
      d.hours += 12;
      h2 = d.hours;
      assert.equal(h1, 4);
      return assert.equal(h2, 16);
    });
    it('should cross date boundaries', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.hours += 20;
      return assert.equal(d.date, 2);
    });
    it('should cross month boundaries', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.hours += 24 * 31;
      return assert.equal(d.month, 9);
    });
    return it('should cross year boundaries', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.hours += 24 * 365;
      return assert.equal(d.year, 2014);
    });
  });
  describe('#minutes', function() {
    it('should set minute', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.minutes = 21;
      return assert.equal(d.getMinutes(), 21);
    });
    it('should return minute', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      return assert.equal(d.minutes, 20);
    });
    it('can be used with -= and += operators', function() {
      var d, m1, m2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.minutes -= 15;
      m1 = d.minutes;
      d.minutes += 20;
      m2 = d.minutes;
      assert.equal(m1, 5);
      return assert.equal(m2, 25);
    });
    it('should cross hour boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.minutes += 50;
      return assert.equal(d.hours, 9);
    });
    it('should cross date boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.minutes += 60 * 24;
      return assert.equal(d.date, 2);
    });
    it('should cross month boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.minutes += 60 * 24 * 31;
      return assert.equal(d.month, 9);
    });
    return it('should cross year boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.minutes += 60 * 24 * 365;
      return assert.equal(d.year, 2014);
    });
  });
  return describe('#seconds', function() {
    it('should set seconds', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.seconds = 21;
      return assert.equal(d.getSeconds(), 21);
    });
    it('should return seconds', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      return assert.equal(d.seconds, 1);
    });
    it('can be used with -= and += operators', function() {
      var d, s1, s2;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.seconds += 20;
      s1 = d.seconds;
      d.seconds -= 5;
      s2 = d.seconds;
      assert.equal(s1, 21);
      return assert.equal(s2, 16);
    });
    it('should cross minutes boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.seconds += 60;
      return assert.equal(d.minutes, 21);
    });
    it('should cross hours boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.seconds += 60 * 60;
      return assert.equal(d.hours, 9);
    });
    it('should cross date boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.seconds += 60 * 60 * 24;
      return assert.equal(d.date, 2);
    });
    it('should cross month boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.seconds += 60 * 60 * 24 * 31;
      return assert.equal(d.month, 9);
    });
    return it('should cross year boundary', function() {
      var d;
      d = new TzTime(2013, 8, 1, 8, 20, 1, 500);
      d.seconds += 60 * 60 * 24 * 365;
      return assert.equal(d.year, 2014);
    });
  });
});
